{
 "title": "Pod availability",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Namespace pods available by deployment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by(deployment) (kube_deployment_status_replicas_available{namespace=\"$namespace\"})",
     "legendFormat": "{{deployment}}"
    },
    {
     "expr": "avg by(statefulset) (kube_statefulset_status_replicas_ready{namespace=\"$namespace\"})",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Namespace pods unschedulable",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(created_by_name) (kube_pod_info{namespace=\"$namespace\"} and on(pod) kube_pod_status_unschedulable{namespace=\"$namespace\"})",
     "legendFormat": "{{created_by_name}}"
    }
   ]
  },
  {
   "title": "Worker node pod count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count by(node) (kube_pod_info{node!=\"\"} unless on(node) kube_node_spec_taint)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Number of nodes that cannot schedule pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg by(node) (kube_node_spec_unschedulable))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "% of node allocated by pod count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count by(node) (kube_pod_info and on(pod) avg by(pod) (kube_pod_status_scheduled{condition=\"true\"})) / on(node) avg by(node) (kube_node_status_allocatable_pods)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "% of node allocated by memory requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (avg by(pod,container,node) (kube_pod_container_resource_requests_memory_bytes)) / on(node) avg by(node) (kube_node_status_capacity_memory_bytes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "% of node allocated by CPU requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(node) (avg by(pod,container,node) (kube_pod_container_resource_requests_cpu_cores)) / on(node) avg by(node) (kube_node_status_capacity_cpu_cores)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}