{
 "title": "Concourse",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Number of containers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(concourse_workers_containers)"
    }
   ]
  },
  {
   "title": "Number of worker nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_time{job=\"concourse_node_exporter\", role=\"concourse-worker\"})"
    }
   ]
  },
  {
   "title": "Number of web nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_time{job=\"concourse_node_exporter\", role=\"concourse-web\"})"
    }
   ]
  },
  {
   "title": "Containers by worker",
   "type": "graph",
   "description": "label_replace(node_uname_info, \"worker\", \"$1\", \"nodename\", \"(.*)\") * on (worker) group_left concourse_workers_containers",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "concourse_workers_containers", "legendFormat": "{{worker}}" }
   ]
  },
  {
   "title": "Web CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~\"gsp-concourse-web.*\"}) without (container_name)"
    }
   ]
  },
  {
   "title": "Web memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"\",pod_name=~\"gsp-concourse-web-.*\"}) by (pod_name)",
     "legendFormat": "Memory usage - {{pod_name}}"
    },
    {
     "expr": " kube_pod_container_resource_requests{resource=\"memory\",pod=~\"gsp-concourse-web.*\"}",
     "legendFormat": "Memory Request - {{pod}}"
    }
   ]
  },
  {
   "title": "Worker disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"concourse-work-dir.*\"} / kubelet_volume_stats_capacity_bytes",
     "legendFormat": "Used disk space - {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Worker CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{pod_name=~\"gsp-concourse-worker.*\"}) without (container_name)",
     "legendFormat": "CPU usage - {{pod_name}}"
    }
   ]
  },
  {
   "title": "Worker memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_name!=\"\",pod_name=~\"gsp-concourse-worker-.*\"}) by (pod_name)",
     "legendFormat": "Memory usage - {{pod_name}}"
    },
    {
     "expr": " kube_pod_container_resource_requests{resource=\"memory\",pod=~\"gsp-concourse-worker.*\"}",
     "legendFormat": "Memory Request - {{pod}}"
    }
   ]
  }
 ]
}